version: "3.7"
services:
  mysql:
    restart: always
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
  web:
    container_name: authentication_web_1
    depends_on:
      - mysql
    restart: on-failure
    build: .
    ports:
      - "8181:8181"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/football_players?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - FB_ID=enter_your_FB_app_ID_for_test
      - FB_SECRET=enter_your_FB_app_Secret_for_test


networks:
  default:
    name: football
